import React, { createContext, useState } from 'react';
export const Context = createContext({
    informations: [],
    setInformations: () => {},
});
export const Provider = ({ children }) => {
    const [informations, setInformations] = useState([
        {
            header: 'Header 1',
            information:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus id lobortis orci. Nam pharetra urna eget eleifend lacinia. Duis ac lectus nibh. Proin quis malesuada risus, nec suscipit odio. Nullam id ornare justo. Aenean a ullamcorper dui. Nam blandit orci nec lorem semper varius. Phasellus nec elit in dolor sagittis convallis at in sapien. Etiam placerat sem eu odio cursus ornare. Praesent at sollicitudin ligula. Integer vel tristique metus. Phasellus lobortis arcu ac nibh mattis, at iaculis orci rhoncus. Nulla vestibulum ipsum in leo scelerisque dictum. In rhoncus lorem dolor, nec lobortis lorem iaculis vitae. Integer egestas urna suscipit tincidunt dictum.Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum non aliquet neque. Aliquam eget augue vitae massa mollis feugiat ac id turpis. Aenean et nisl quis neque ultricies tristique at vel nisi. Aenean vehicula ante nec augue porttitor fermentum. Phasellus pellentesque elementum purus, ultricies tincidunt nulla rhoncus et. Curabitur nec mauris odio.Nullam porta, ipsum ac efficitur feugiat, sapien nunc facilisis lorem, quis sodales massa lectus vel dolor. Pellentesque eu felis tincidunt, vestibulum odio id, bibendum metus. Curabitur congue nisl purus, ut accumsan purus laoreet a. Nam eget pharetra eros. Cras porttitor nulla sapien, eu volutpat dolor commodo ",
        },
        {
            header: 'Header 2',
            information:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus id lobortis orci. Nam pharetra urna eget eleifend lacinia. Duis ac lectus nibh. Proin quis malesuada risus, nec suscipit odio. Nullam id ornare justo. Aenean a ullamcorper dui. Nam blandit orci nec lorem semper varius. Phasellus nec elit in dolor sagittis convallis at in sapien. Etiam placerat sem eu odio cursus ornare. Praesent at sollicitudin ligula. Integer vel tristique metus. Phasellus lobortis arcu ac nibh mattis, at iaculis orci rhoncus. Nulla vestibulum ipsum in leo scelerisque dictum. In rhoncus lorem dolor, nec lobortis lorem iaculis vitae. Integer egestas urna suscipit tincidunt dictum.Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum non aliquet neque. Aliquam eget augue vitae massa mollis feugiat ac id turpis. Aenean et nisl quis neque ultricies tristique at vel nisi. Aenean vehicula ante nec augue porttitor fermentum. Phasellus pellentesque elementum purus, ultricies tincidunt nulla rhoncus et. Curabitur nec mauris odio.Nullam porta, ipsum ac efficitur feugiat, sapien nunc facilisis lorem, quis sodales massa lectus vel dolor. Pellentesque eu felis tincidunt, vestibulum odio id, bibendum metus. Curabitur congue nisl purus, ut accumsan purus laoreet a. Nam eget pharetra eros. Cras porttitor nulla sapien, eu volutpat dolor commodo ",
        },
        {
            header: 'Header 3',
            information:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus id lobortis orci. Nam pharetra urna eget eleifend lacinia. Duis ac lectus nibh. Proin quis malesuada risus, nec suscipit odio. Nullam id ornare justo. Aenean a ullamcorper dui. Nam blandit orci nec lorem semper varius. Phasellus nec elit in dolor sagittis convallis at in sapien. Etiam placerat sem eu odio cursus ornare. Praesent at sollicitudin ligula. Integer vel tristique metus. Phasellus lobortis arcu ac nibh mattis, at iaculis orci rhoncus. Nulla vestibulum ipsum in leo scelerisque dictum. In rhoncus lorem dolor, nec lobortis lorem iaculis vitae. Integer egestas urna suscipit tincidunt dictum.Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum non aliquet neque. Aliquam eget augue vitae massa mollis feugiat ac id turpis. Aenean et nisl quis neque ultricies tristique at vel nisi. Aenean vehicula ante nec augue porttitor fermentum. Phasellus pellentesque elementum purus, ultricies tincidunt nulla rhoncus et. Curabitur nec mauris odio.Nullam porta, ipsum ac efficitur feugiat, sapien nunc facilisis lorem, quis sodales massa lectus vel dolor. Pellentesque eu felis tincidunt, vestibulum odio id, bibendum metus. Curabitur congue nisl purus, ut accumsan purus laoreet a. Nam eget pharetra eros. Cras porttitor nulla sapien, eu volutpat dolor commodo ",
        },
        {
            header: 'Header 4',
            information:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus id lobortis orci. Nam pharetra urna eget eleifend lacinia. Duis ac lectus nibh. Proin quis malesuada risus, nec suscipit odio. Nullam id ornare justo. Aenean a ullamcorper dui. Nam blandit orci nec lorem semper varius. Phasellus nec elit in dolor sagittis convallis at in sapien. Etiam placerat sem eu odio cursus ornare. Praesent at sollicitudin ligula. Integer vel tristique metus. Phasellus lobortis arcu ac nibh mattis, at iaculis orci rhoncus. Nulla vestibulum ipsum in leo scelerisque dictum. In rhoncus lorem dolor, nec lobortis lorem iaculis vitae. Integer egestas urna suscipit tincidunt dictum.Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum non aliquet neque. Aliquam eget augue vitae massa mollis feugiat ac id turpis. Aenean et nisl quis neque ultricies tristique at vel nisi. Aenean vehicula ante nec augue porttitor fermentum. Phasellus pellentesque elementum purus, ultricies tincidunt nulla rhoncus et. Curabitur nec mauris odio.Nullam porta, ipsum ac efficitur feugiat, sapien nunc facilisis lorem, quis sodales massa lectus vel dolor. Pellentesque eu felis tincidunt, vestibulum odio id, bibendum metus. Curabitur congue nisl purus, ut accumsan purus laoreet a. Nam eget pharetra eros. Cras porttitor nulla sapien, eu volutpat dolor commodo ",
        },
    ]);

    return (
        <Context.Provider value={{ informations, setInformations }}>
            {children}
        </Context.Provider>
    );
};